plugin:
    name: 'Code200.developer::lang.plugin.name'
    description: 'Code200.developer::lang.plugin.description'
    author: 'Miha Trtnik'
    icon: oc-icon-beer
    homepage: 'https://github.com/webeks/code200-developer'
